### ISSUE TITLE
Issue with RangeError 

### ISSUE THREAD

**Issue by Braendstrup** [racehub-io/f1-telemetry-client#61]
**Describe the bug**
When trying to console.log PACKETS.carTelemetry data a _RangeError: Offset is outside the bounds of the DataView_ exception is thrown.

**To Reproduce**
Using F1 2021 configuration
Tried hotlapping while using npm package, following the example in the readme. 

**Expected behavior**
Should not throw exception and die.

**Screenshots/Additional information**
```
{ m_speed: 0,
       m_clutch: 0,
       m_gear: 0,
       m_engineRPM: 0,
       m_drs: 0,
       m_revLightsPercent: 0,
       m_brakesTemperature: [Array],
       m_tyresSurfaceTemperature: [Array],
       m_tyresInnerTemperature: [Array],
       m_engineTemperature: 0,
       m_tyresPressure: [Array] } ] }
undefined:109
$tmp1.m_ersHarvestedThisLapMGUH = dataView.getFloat32(offset, true);
                                           ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.getFloat32 (<anonymous>)
    at PacketCarStatusDataParser.eval [as compiled] (eval at Parser.compile (/home/pi/Downloads/F1telemetry/node_modules/binary-parser/dist/binary_parser.js:473:25), <anonymous>:109:44)
    at PacketCarStatusDataParser.Parser.parse (/home/pi/Downloads/F1telemetry/node_modules/binary-parser/dist/binary_parser.js:523:21)
    at PacketCarStatusDataParser.fromBuffer (/home/pi/Downloads/F1telemetry/node_modules/f1-telemetry-client/build/src/parsers/F1Parser.js:11:21)
    at new PacketCarStatusDataParser (/home/pi/Downloads/F1telemetry/node_modules/f1-telemetry-client/build/src/parsers/packets/PacketCarStatusDataParser.js:17:26)
    at Function.parseBufferMessage (/home/pi/Downloads/F1telemetry/node_modules/f1-telemetry-client/build/src/index.js:48:28)
    at F1TelemetryClient.handleMessage (/home/pi/Downloads/F1telemetry/node_modules/f1-telemetry-client/build/src/index.js:118:49)
    at Socket.socket.on (/home/pi/Downloads/F1telemetry/node_modules/f1-telemetry-client/build/src/index.js:155:47)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
```

**Comment by jonybur** [comment]
Hey @Braendstrup. This should be fixed on 0.1.26 which has just been released. Please let me know if it's working and I'll close this ticket. Thanks
